version: '3.4'

services:
  web:
    build:
      context: ./site_flask/
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      FLASK_RUN_PORT: 5001
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_APP: "main.py"
    ports:
      - "5001:5001"